[MOD] mrp_repair_full_editable: avoid change invoice_method after the repair is confirmed
odoomrp/odoomrp-wip pull request #1314
Opened 2016-10-19 10:15 UTC by esthermm

2016-10-19 11:49 UTC, esthermm commented
@odoomrp/developers review pls

2016-10-19 13:35 UTC, oihane commented
@esthermm estas haciendo lo contrario, por defecto ese campo es solo editable para el estado borrador.

2016-10-19 13:59 UTC, oihane approved these changes
Perdona @esthermm no se porque lo he leído al revés (pero varias veces). Está bien.

Añade comentario en el README de que no se puede hacer ese campo editable, y porque.

2016-10-20 13:00 UTC, Daniel-CA commented
:+1:

2016-10-24 13:42 UTC, oihane requested changes

2016-10-24 13:42 UTC, oihane commented on mrp_repair_full_editable/README.rst
> +draft orders.
After a repair order confirmation if a user changes the invoice method, the workflow won't work properly. Therefore, the invoice method has to be editable **only** in draft orders.

2016-10-25 07:27 UTC, agaldona commented
:+1: LGTM

2016-10-25 07:31 UTC, oihane approved these changes

2016-10-25 07:32 UTC, merged