[IMP] mrp_operations_rejected_quantity: In OT, allowing consume more …
odoomrp/odoomrp-wip pull request #1323
Opened 2016-10-31 10:17 UTC by alfredoavanzosc

…than planned.
Permitir consumir mas de lo planificado en una OT.

2016-10-31 15:01 UTC, alfredoavanzosc commented
@agaldona , @esthermm , @Daniel-CA ... ¿Le podéis echar un vistazo por favor?. eskerik asko.

2016-10-31 16:22 UTC, agaldona requested changes

2016-10-31 16:22 UTC, agaldona commented on mrp_operations_rejected_quantity/wizard/mrp_work_order_produce.py
> +            consume_lines.append(
¿Aquí que pasa si el material tiene un quant asignado con lote? ¿O si tiene varios quants? No lo estas teniendo en cuenta.

2016-11-02 07:23 UTC, alfredoavanzosc commented on mrp_operations_rejected_quantity/wizard/mrp_work_order_produce.py
> +            consume_lines.append(
Que hay @agaldona , esta función solo se va a ejecutar cuando se consume/produce en una OT, y sólo se va a ejecutar esta función cuando se vaya a consumir/producir más de lo planificado. Esto lo ha solicitó en su día @anajuaristi.

2016-11-02 07:47 UTC, agaldona approved these changes

2016-11-02 14:48 UTC, merged